import pandas as pd
import json

df = pd.DataFrame()

# For each prompt, please spcify the returned type you want.
prompts = [
    # easy ones
    "How many nodes are in the graph? Return only the number.",
    "How many nodes and edges are in the graph? Return a list.",
    "Add a label app:prod to nodes with address prefix 10.0 and add the label app:user to nodes with address prefix 40.79. Return the networkx graph object.",
    "Show me the unique labels and the number of nodes per label. Return a table with header 'Label', 'Number of Nodes' on the first row.",
    "Remove the label 'role:0' from all the nodes. Return the networkx graph object.",
    "What are max degree and min degree in the graph? Return a table with header 'Max degree', 'Min degree' on the first row.",
    "Color all of the nodes with label 'role:1' purple. Return the networkx graph object.",
    "Color the node with max degree red and min degree green. Return the networkx graph object.",

    # medium ones
    "How many nodes are there that have an edge to nodes with labels 'role:1' or 'role:2' and doesn't have either of those labels? Return only the number.",
    "How much traffic in bytes between microseg 'role:0' and 'role:1'? Return only the number.",
    "Find nodes with top 10 number of degrees, list nodes, labels and number of degrees. Return a table without headers.",
    "Color the nodes that can be connect to nodes with label 'role:1' with green. Return the networkx graph object.",
    "Use Kernighan–Lin algorithm to cut the graph into two parts such that the number of edges between the cuts is same. Color two parts with red and blue. Return the networkx graph object.",
    "Calculate the total byte weight of edges incident on each node, use kmeans clustering to cluster the total byte weights into 5 clusters. Add a label 'cluster:{index}' to each node. Return the networkx graph object.",

    # hard ones
    "How many maximal cliques are in the graph? Return only the number.",
    "Use spectral partitioning to bisect the network such that the number of nodes on either side of the cut is equal. Color two parts with red and blue. Return the networkx graph object.",
    "How many unique nodes have edges to nodes with label 'role:1' and doesn't contain the label 'role:0'? Return only the number.",
    "Show me the unique IP address prefix and the number of nodes per prefix. Return a table without headers.",
    "Delete all edges whose byte weight is less than the median byte weight in the whole graph without using the statistics library. Make sure to compute the median and not the mean. Return the networkx graph object.",
    "What is the average byte weight and connection weight of edges incident on nodes with labels 'role:0'? Return a table with header 'Average byte weight', 'Average connection weight' on the first row.",

]

answers=[
    # 8 easy ones
    "\ndef ground_truth_process_graph(graph_data):\n    return_object = {\n        'type': 'text',\n        'data': str(len(graph_data.nodes))\n    }\n    return return_object",
    "\ndef ground_truth_process_graph(graph_data):\n    num_nodes = len(graph_data.nodes())\n    num_edges = len(graph_data.edges())\n    return_object = {\n        'type': 'list',\n        'data': [num_nodes, num_edges]\n    }\n    return return_object",
    "\ndef ground_truth_process_graph(graph_data):\n    # Iterate over all nodes in the graph\n    for node in graph_data.nodes():\n        # Get the IP address of the node\n        ip_address = graph_data.nodes[node]['ip_address']\n        \n        # Check if the IP address starts with '10.0'\n        if ip_address.startswith('10.0'):\n            # If it does, add the label 'app:prod' to the node\n            graph_data.nodes[node]['labels'].append('app:prod')\n        \n        # Check if the IP address starts with '40.79'\n        elif ip_address.startswith('40.79'):\n            # If it does, add the label 'app:user' to the node\n            graph_data.nodes[node]['labels'].append('app:user')\n    \n    # Return the modified graph\n    return_object = {'type': 'graph', 'data': nx.node_link_data(graph_data)}\n    return return_object\n",
    "\ndef ground_truth_process_graph(graph_data):\n    labels = {}\n    for node in graph_data.nodes():\n        for label in graph_data.nodes[node]['labels']:\n            if label not in labels:\n                labels[label] = 1\n            else:\n                labels[label] += 1\n    return_object = {\n        'type': 'table',\n        'data': [['Label', 'Number of Nodes']]\n    }\n    for label, count in labels.items():\n        return_object['data'].append([label, count])\n    return return_object",
    "\ndef ground_truth_process_graph(graph_data):\n    # Iterate over all nodes in the graph\n    for node in graph_data.nodes():\n        # Check if the node has a 'role:0' label\n        if 'role:0' in graph_data.nodes[node]['labels']:\n            # Remove the 'role:0' label from the node\n            graph_data.nodes[node]['labels'].remove('role:0')\n    \n    # Return the modified graph\n    return_object = {'type': 'graph', 'data': nx.node_link_data(graph_data)}\n    return return_object\n",
    "\ndef ground_truth_process_graph(graph_data):\n    max_degree = 0\n    min_degree = float('inf')\n    for node in graph_data.nodes():\n        degree = graph_data.degree(node)\n        if degree > max_degree:\n            max_degree = degree\n        if degree < min_degree:\n            min_degree = degree\n    return_object = {\n        'type': 'table',\n        'data': [['Max degree', 'Min degree'], [max_degree, min_degree]]\n    }\n    return return_object",
    "\ndef ground_truth_process_graph(graph_data):\n    for node in graph_data.nodes():\n        if 'role:1' in graph_data.nodes[node]['labels']:\n            graph_data.nodes[node]['color'] = 'purple'\n    return_object = {\n        'type': 'graph',\n        'data': nx.node_link_data(graph_data)\n    }\n    return return_object",
    "\ndef ground_truth_process_graph(graph_data):\n    max_degree = 0\n    min_degree = float('inf')\n    max_node = None\n    min_node = None\n    for node in graph_data.nodes():\n        degree = graph_data.degree(node)\n        if degree > max_degree:\n            max_degree = degree\n            max_node = node\n        if degree < min_degree:\n            min_degree = degree\n            min_node = node\n    graph_data.nodes[max_node]['color'] = 'red'\n    graph_data.nodes[min_node]['color'] = 'green'\n    return_object = {\n        'type': 'graph',\n        'data': nx.node_link_data(graph_data)\n    }\n    return return_object",

    # 8 medium ones
    "\ndef ground_truth_process_graph(graph_data):\n    # Initialize a set to store the nodes with labels 'role:1' or 'role:2'\n    role_nodes = set()\n    # Initialize a set to store the nodes that have an edge to nodes with labels 'role:1' or 'role:2'\n    connected_nodes = set()\n\n    # Iterate over all nodes in the graph\n    for node in graph_data.nodes():\n        # Check if the node has a label 'role:1' or 'role:2'\n        if any(label.startswith('role:1') or label.startswith('role:2') for label in graph_data.nodes[node]['labels']):\n            # Add the node to the set of role nodes\n            role_nodes.add(node)\n\n    # Iterate over all edges in the graph\n    for edge in graph_data.edges():\n        # Check if the source node or the target node is a role node\n        if edge[0] in role_nodes or edge[1] in role_nodes:\n            # Add the other node to the set of connected nodes\n            connected_nodes.add(edge[0] if edge[1] in role_nodes else edge[1])\n\n    # Subtract the set of role nodes from the set of connected nodes to get the nodes that are connected to role nodes but do not have the role label themselves\n    result_nodes = connected_nodes - role_nodes\n\n    # Return the number of such nodes\n    return_object = {'type': 'text', 'data': str(len(result_nodes))}\n    return return_object\n",
    "\ndef ground_truth_process_graph(graph_data):\n    # Initialize the total bytes to 0\n    total_bytes = 0\n\n    # Iterate over all the edges in the graph\n    for edge in graph_data.edges(data=True):\n        # Check if the source and target nodes have the roles 'role:0' and 'role:1'\n        if 'role:0' in graph_data.nodes[edge[0]]['labels'] and 'role:1' in graph_data.nodes[edge[1]]['labels']:\n            # Add the byte_weight of the edge to the total bytes\n            total_bytes += edge[2]['byte_weight']\n        elif 'role:1' in graph_data.nodes[edge[0]]['labels'] and 'role:0' in graph_data.nodes[edge[1]]['labels']:\n            # Add the byte_weight of the edge to the total bytes\n            total_bytes += edge[2]['byte_weight']\n\n    # Return the total bytes as a dict with 'type' and 'data' keys\n    return_object = {'type': 'text', 'data': str(total_bytes)}\n    return return_object\n",
    "\ndef ground_truth_process_graph(graph_data):\n    degree_list = []\n    for node in graph_data.nodes():\n        degree_list.append((node, graph_data.degree(node)))\n    degree_list.sort(key=lambda x: x[1], reverse=True)\n    top_10_degree_list = degree_list[:10]\n    return_object = {\n        'type': 'table',\n        'data': [[node, graph_data.nodes[node]['labels'], degree] for node, degree in top_10_degree_list]\n    }\n    return return_object",
    "\ndef ground_truth_process_graph(graph_data):\n    # Iterate over all nodes in the graph\n    for node in graph_data.nodes():\n        # Check if the node has a label 'role:1'\n        if 'role:1' in graph_data.nodes[node]['labels']:\n            # Iterate over all neighbors of the node\n            for neighbor in graph_data.neighbors(node):\n                # Color the neighbor nodes with green\n                graph_data.nodes[neighbor]['color'] = 'green'\n    \n    # Prepare the return object\n    return_object = {\n        'type': 'graph',\n        'data': nx.node_link_data(graph_data)  # Convert the graph data to a format that can be used with D3.js\n    }\n    \n    return return_object\n",
    "\ndef ground_truth_process_graph(graph_data):\n    # Convert the directed graph to an undirected graph\n    undirected_graph = graph_data.to_undirected()\n    \n    # Use Kernighan–Lin algorithm to divide the graph into two parts\n    partition = nx.algorithms.community.kernighan_lin_bisection(undirected_graph, weight='byte_weight')\n    \n    # Assign a color attribute to each node in the graph\n    for node in graph_data.nodes():\n        if node in partition[0]:\n            graph_data.nodes[node]['color'] = 'red'\n        else:\n            graph_data.nodes[node]['color'] = 'blue'\n    \n    # Return the modified networkx graph object\n    return_object = {\n        'type': 'graph',\n        'data': graph_data\n    }\n    return return_object\n",
    "\ndef ground_truth_process_graph(graph_data):\n    # Calculate the total byte weight of all edges incident on each node\n    byte_weights = {}\n    for node in graph_data.nodes():\n        byte_weight = sum([graph_data.edges[edge]['byte_weight'] for edge in graph_data.edges(node)])\n        byte_weights[node] = byte_weight\n\n    # Perform kmeans clustering into 5 clusters\n    byte_weights_list = list(byte_weights.values())\n    byte_weights_array = np.array(byte_weights_list).reshape(-1, 1)\n    kmeans = KMeans(n_clusters=5, random_state=0).fit(byte_weights_array)\n    labels = kmeans.labels_\n\n    # Add a label 'cluster:{index}' to each node\n    for i, node in enumerate(graph_data.nodes()):\n        graph_data.nodes[node]['labels'].append('cluster:{}'.format(labels[i]))\n\n    return_object = {\n        'type': 'graph',\n        'data': nx.node_link_data(graph_data)\n    }\n    return return_object",

    # 8 hard ones
    "\ndef ground_truth_process_graph(graph_data):\n    # Convert the graph to undirected if it is not\n    if graph_data.is_directed():\n        graph_data = graph_data.to_undirected()\n        \n    return_object = {\n        'type': 'text',\n        'data': str(len(list(nx.find_cliques(graph_data))))\n    }\n    return return_object",
    "\ndef ground_truth_process_graph(graph_data):\n    # Convert the directed graph to an undirected graph\n    undirected_graph = graph_data.to_undirected()\n\n    # Use spectral partitioning to bisect the networkx graph into two equal halves\n    laplacian = nx.normalized_laplacian_matrix(undirected_graph)\n    eigvals, eigvecs = np.linalg.eig(laplacian.A)\n    partition = eigvecs[:, np.argsort(eigvals)[1]] > 0\n\n    # Assign a unique color to each of the two groups of nodes resulting from the bisection\n    for i, node in enumerate(graph_data.nodes()):\n        graph_data.nodes[node]['color'] = 'red' if partition[i] else 'blue'\n\n    # Return the modified networkx graph object with the nodes colored based on the bisection\n    return_object = {\n        'type': 'graph',\n        'data': nx.node_link_data(graph_data)\n    }\n    return return_object",
    "\ndef ground_truth_process_graph(graph_data):\n    role1_nodes = [node for node, data in graph_data.nodes(data=True) if 'role:1' in data['labels']]\n    connected_nodes = set()\n    for node in role1_nodes:\n        connected_nodes.update([n for n in graph_data.neighbors(node) if 'role:0' not in graph_data.nodes[n]['labels']])\n    return_object = {\n        'type': 'text',\n        'data': str(len(connected_nodes))\n    }\n    return return_object",
    "\ndef ground_truth_process_graph(graph_data):\n    # Initialize a dictionary to store the IP address prefix and the number of nodes per prefix\n    prefix_count = {}\n    \n    # Iterate through each node in the graph\n    for node in graph_data.nodes():\n        # Get the IP address of the node\n        ip_address = graph_data.nodes[node]['ip_address']\n        # Get the /8 IP prefix\n        prefix = ip_address.split('.')[0]\n        # Check if the prefix is already in the dictionary\n        if prefix in prefix_count:\n            # If it is, increment the count\n            prefix_count[prefix] += 1\n        else:\n            # If it isn't, add it to the dictionary and set the count to 1\n            prefix_count[prefix] = 1\n    \n    # Create a list of lists to store the data\n    table_data = []\n    # Iterate through the dictionary\n    for prefix, count in prefix_count.items():\n        # Append the prefix and count to the list\n        table_data.append([prefix, count])\n    \n    # Return the data in a JSON object\n    return_object = {\n        'type': 'table',\n        'data': table_data\n    }\n    return return_object",
    "\ndef ground_truth_process_graph(graph_data):\n    # Traverse through all the edges in the networkx graph and collect all the byte weights in a list.\n    byte_weights = [graph_data.edges[edge]['byte_weight'] for edge in graph_data.edges()]\n\n    # Sort the list of byte weights and find the median value. \n    byte_weights.sort()\n    length = len(byte_weights)\n    if length % 2 == 0:\n        median = (byte_weights[length // 2 - 1] + byte_weights[length // 2]) / 2\n    else:\n        median = byte_weights[length // 2]\n\n    # Iterate through all the edges again and remove any edge whose byte weight is less than the computed median.\n    edges_to_remove = [edge for edge in graph_data.edges() if graph_data.edges[edge]['byte_weight'] < median]\n    graph_data.remove_edges_from(edges_to_remove)\n\n    # Return the modified networkx graph object\n    return_object = {\n        'type': 'graph',\n        'data': nx.node_link_data(graph_data)\n    }\n    return return_object\n",
    "\ndef ground_truth_process_graph(graph_data):\n    total_byte_weight = 0\n    total_connection_weight = 0\n    count = 0\n\n    for node in graph_data.nodes():\n        labels = graph_data.nodes[node]['labels']\n        if 'role:0' in labels:\n            edges = graph_data.edges(node, data=True)\n            for edge in edges:\n                total_byte_weight += edge[2]['byte_weight']\n                total_connection_weight += edge[2]['connection_weight']\n                count += 1\n\n    average_byte_weight = total_byte_weight / count if count > 0 else 0\n    average_connection_weight = total_connection_weight / count if count > 0 else 0\n\n    return_object = {\n        'type': 'table',\n        'data': [['Average byte weight', 'Average connection weight'], [average_byte_weight, average_connection_weight]]\n    }\n\n    return return_object",
]


df['prompt'] = prompts
df['answer'] = answers


allData = df.set_index('prompt').T.to_dict('records')[0]
with open('prompt_golden_ans.json', "w") as f:
    json.dump(allData, f)

with open('prompt_golden_ans.json', "r") as fr:
    allAnswer = json.load(fr)

# # Find all available prompts
# prompt_exampe='How many nodes are in the graph?'
#
# if prompt_exampe in allAnswer.keys():
#     print("True")
#
# import pdb; pdb.set_trace()
